name: 'GHAS Alert Mapper'
description: 'Map GHAS alerts between GitHub repositories.'
author: 'Stefan Petrushevski @theztefan'

branding:
  icon: 'heart'
  color: 'purple'

inputs:
  original_repository:
    description:
      'Full name of the original repository - organization/repository'
    required: true
  original_endpoint:
    description: 'Endpoint for the original repository - https://api.github.com'
    required: false
    default: 'https://api.github.com'
  original_token:
    description: 'GitHub Access Token for the original repository'
    required: true
  target_repository:
    description: 'Full name of the target repository - organization/repository'
    required: true
  target_endpoint:
    description: 'Endpoint for the target repository - https://api.github.com'
    required: false
    default: 'https://api.github.com'
  target_token:
    description: 'GitHub Access Token for the target repository'
    required: true
  dry_run:
    description: 'Dry run the action without making any changes'
    required: true
    default: 'true'
  alert_types:
    description:
      'Comma separated list of alert types to process (all, secret-scanning,
      code-scanning, dependabot).'
    required: false
    default: 'all'
  matching-level:
    description: 'Matching level for the action (exact, loose).'
    required: false
    default: 'exact'

outputs:
  report_file:
    description: 'The file containing the report of the action'

runs:
  using: node20
  main: dist/index.js
