name: 'GHAS Alert Mapper'
description: 'Map GHAS alerts between GitHub repositories.'
author: 'Stefan Petrushevski @theztefan'

branding:
  icon: 'heart'
  color: 'purple'

inputs:
  original-repository:
    description:
      'Full name of the original repository - organization/repository'
    required: true
  original-endpoint:
    description: 'Endpoint for the original repository - https://api.github.com'
    required: false
    default: 'https://api.github.com'
  original-token:
    description: 'GitHub Access Token for the original repository'
    required: true
  target-repository:
    description: 'Full name of the target repository - organization/repository'
    required: true
  target-endpoint:
    description: 'Endpoint for the target repository - https://api.github.com'
    required: false
    default: 'https://api.github.com'
  target-token:
    description: 'GitHub Access Token for the target repository'
    required: true
  dry-run:
    description: 'Dry run the action without making any changes'
    required: true
    default: 'true'

# Define your outputs here.
outputs:
  report-file:
    description: 'The file containing the report of the action'

runs:
  using: node20
  main: dist/index.js
